### ISSUE TITLE
Does this work?

### ISSUE THREAD

**Issue by torsteinelv** [maxx-ukoo/jk-bms2pylontech#1]
Having some troubles understanding how I can test this? Or is it not complete jet? Is there any way to contribute to this project?

**Comment by maxx-ukoo** [comment]
I didn't test with real solar inverter. Due war in Ukraine i not able to order battery pack to test it with real inverter. Tested with JKBMS and raspberry Pi as CAN receiver. I saw correct pdata on CAN BUS. Branch mk_add_LCD_optional should work.

**Comment by torsteinelv** [comment]
Aha. I have an inverter here i would love to test it on. But im not sure on how to do this?

**Comment by maxx-ukoo** [comment]
Prepare board with STM32, CAN tranciver. Build and flash firmware, connect board to BMS and inverter and test. But i not recomment test it in current state if you don't know hot to do it without help. When i will able buy battery pack i will return to this project.

**Comment by torsteinelv** [comment]
Aha. Thanks for your reply. Have ordered the neccacary parts. 🙂

Was realy hoping this could run in the same device as the jk bms esp33 you had in the references 🙂

**Comment by Xach-s-usami** [comment]
hello, i'm from ukraine too!  I have an inverter and a battery, is it possible to contact you somehow to help you?

**Comment by maxx-ukoo** [comment]
@Xach-s-usami you can prepare hardware, flash firmware and privide feedback. I don't know how you can help me in another way. If you have another ideas you can find email on this page - https://www.maxx.net.ua/?page_id=447
